# Generated by Django 5.2.5 on 2025-11-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plato',
            name='imagen_plato',
            field=models.ImageField(blank=True, null=True, upload_to='platos/'),
        ),
    ]
