# Generated by Django 5.2.5 on 2025-11-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_ingrediente_stock_plato_imagen_plato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plato',
            old_name='imagen_plato',
            new_name='imagen',
        ),
    ]
