# Generated by Django 5.2.6 on 2025-11-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_rename_imagen_plato_plato_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
